server:
  port: 7071
spring:
  application:
    name: mservice-myzuul
eureka:
  client:
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8761/eureka/

  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
