server:
  port: 7071
spring:
  application:
    name: mservice-myzuul
eureka:
  client:
    server-url:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8761/eureka/

  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false

zuul:
  ignoredPatterns: /**/admin/**   # 忽略所有包括/admin/的路径
  ignored-services: '*'     #忽略所有微服务，只使用路由转发
  prefix: /admin/
  routes:
    router1:
     service-id: microservice-user
     path: /service/**
    router2:
     service-id:  microservice-custom  # 微服务id
     path : /servicecustom/**
     strip-prefix: false
    router3:
     url: http://www.baidu.com/ # 指定的url
     path: /gotobaidu    # 访问这个链接直接跳转百度
    forwardrouter:
      path: /admin/custom/**
      url: forward:/admin/servicecustom/**

# 请求日志打印级别
logging:
  level:
    com.netflix: DEBUG