spring:
  application:
    name: microservice-custom
server:
  port: 8081
## 取消eureka注册. 直接使用ribbon 进行负载均衡
microservice-provider-user:
  ribbon:
    listOfServers: localhost:8001,localhost:8002
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

