spring:
  application:
    name: microservice-Turbine
server:
  port: 6082
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka:
  client:
    region: beijing
    serviceUrl:
      defaultZone: http://liuyang:7890@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
turbine:
  appConfig: microservice-custom,microservice-custom2
  clusterNameExpression: "'default'"