spring:
  application:
    name: microservice-custom
server:
  port: 8089
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka:
  client:
    region: beijing
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
feign:
  hystrix:
    enabled: true

hystrix:
    command:
        "microservice-custom":
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 3000