spring:
  application:
    name: microservice-custom
server:
  port: 8081
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka:
  client:
    region: beijing
    serviceUrl:
      defaultZone: http://liuyang:7890@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
microservice-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    
feign:
  hystrix:
    enabled: true