spring:
   application:
      name: eureka
eureka:
   instance:
      app-group-name: "beijingmservice"
      hostname: e1
      prefer-ip-address: true
   client:
      region: beijing
      service-url:
         defaultZone: http://e2:8760/eureka
server:
  port: 8761

