spring:
   application:
      name: mservice-test-file   
eureka:
   instance:
      app-group-name: "beijingmservice"
      hostname: e1
      prefer-ip-address: true
   client:
      region: beijing
      service-url:
         defaultZone: http://e1:8762/eureka
server:
  port: 8760



