server:
  port: 7000
spring:
   application:
      name: mservice-config-server
   cloud:
      config:
        server:
          git:
            uri: https://gitee.com/aaronrao/spring-cloud-config-test.git
            username:
            password: