server:
  port: 7000
spring:
   application:
      name: mservice-config-server
   cloud:
      config:
        server:
          git:
            uri: https://github.com/AnyYANG/MySpringBoot
            searchPaths: pro*

